# Generated by Django 3.2.8 on 2021-10-07 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('e_mail', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(unique_for_date=True, unique_for_month=True, unique_for_year=True)),
                ('end_date', models.DateTimeField(unique_for_date=True, unique_for_month=True, unique_for_year=True)),
                ('service', models.CharField(choices=[('Mani', 'Mani'), ('Pedi', 'Pedi')], max_length=50)),
                ('type', models.CharField(choices=[('Semi', 'Semi'), ('Gel', 'Gel'), ('Classic', 'Classic')], max_length=50)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.client')),
            ],
        ),
    ]
